/**
 * TRAVNIFY — Shared Currency Utility
 * Covers all major Razorpay-supported + world currencies.
 * Conversion rates: approximate 1 INR → target currency.
 */

// ─── Currency Definitions ──────────────────────────────────────
export const CURRENCIES = [
  { code: 'INR', symbol: '₹',   name: 'Indian Rupee' },
  { code: 'USD', symbol: '$',   name: 'US Dollar' },
  { code: 'EUR', symbol: '€',   name: 'Euro' },
  { code: 'GBP', symbol: '£',   name: 'British Pound' },
  { code: 'AUD', symbol: 'A$',  name: 'Australian Dollar' },
  { code: 'CAD', symbol: 'C$',  name: 'Canadian Dollar' },
  { code: 'SGD', symbol: 'S$',  name: 'Singapore Dollar' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
  { code: 'JPY', symbol: '¥',   name: 'Japanese Yen' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc' },
  { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar' },
  { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar' },
  { code: 'SEK', symbol: 'kr',  name: 'Swedish Krona' },
  { code: 'NOK', symbol: 'kr',  name: 'Norwegian Krone' },
  { code: 'DKK', symbol: 'kr',  name: 'Danish Krone' },
  { code: 'CNY', symbol: '¥',   name: 'Chinese Yuan' },
  { code: 'KRW', symbol: '₩',   name: 'South Korean Won' },
  { code: 'THB', symbol: '฿',   name: 'Thai Baht' },
  { code: 'IDR', symbol: 'Rp',  name: 'Indonesian Rupiah' },
  { code: 'MYR', symbol: 'RM',  name: 'Malaysian Ringgit' },
  { code: 'PHP', symbol: '₱',   name: 'Philippine Peso' },
  { code: 'VND', symbol: '₫',   name: 'Vietnamese Dong' },
  { code: 'BDT', symbol: '৳',   name: 'Bangladeshi Taka' },
  { code: 'PKR', symbol: '₨',   name: 'Pakistani Rupee' },
  { code: 'LKR', symbol: 'Rs',  name: 'Sri Lankan Rupee' },
  { code: 'NPR', symbol: 'Rs',  name: 'Nepalese Rupee' },
  { code: 'SAR', symbol: '﷼',   name: 'Saudi Riyal' },
  { code: 'QAR', symbol: '﷼',   name: 'Qatari Riyal' },
  { code: 'KWD', symbol: 'KD',  name: 'Kuwaiti Dinar' },
  { code: 'BHD', symbol: 'BD',  name: 'Bahraini Dinar' },
  { code: 'OMR', symbol: 'ر.ع', name: 'Omani Rial' },
  { code: 'JOD', symbol: 'JD',  name: 'Jordanian Dinar' },
  { code: 'EGP', symbol: 'E£',  name: 'Egyptian Pound' },
  { code: 'ZAR', symbol: 'R',   name: 'South African Rand' },
  { code: 'NGN', symbol: '₦',   name: 'Nigerian Naira' },
  { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling' },
  { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi' },
  { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling' },
  { code: 'BRL', symbol: 'R$',  name: 'Brazilian Real' },
  { code: 'MXN', symbol: '$',   name: 'Mexican Peso' },
  { code: 'ARS', symbol: '$',   name: 'Argentine Peso' },
  { code: 'COP', symbol: '$',   name: 'Colombian Peso' },
  { code: 'CLP', symbol: '$',   name: 'Chilean Peso' },
  { code: 'PEN', symbol: 'S/',  name: 'Peruvian Sol' },
  { code: 'TRY', symbol: '₺',   name: 'Turkish Lira' },
  { code: 'PLN', symbol: 'zł',  name: 'Polish Zloty' },
  { code: 'CZK', symbol: 'Kč',  name: 'Czech Koruna' },
  { code: 'HUF', symbol: 'Ft',  name: 'Hungarian Forint' },
  { code: 'RON', symbol: 'lei', name: 'Romanian Leu' },
  { code: 'UAH', symbol: '₴',   name: 'Ukrainian Hryvnia' },
  { code: 'RUB', symbol: '₽',   name: 'Russian Ruble' },
  { code: 'ILS', symbol: '₪',   name: 'Israeli New Shekel' },
  { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham' },
  { code: 'DZD', symbol: 'DA',  name: 'Algerian Dinar' },
  { code: 'TND', symbol: 'DT',  name: 'Tunisian Dinar' },
  { code: 'ETB', symbol: 'Br',  name: 'Ethiopian Birr' },
  { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling' },
  { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc' },
  { code: 'XAF', symbol: 'FCFA',name: 'Central African CFA Franc' },
  { code: 'CRC', symbol: '₡',   name: 'Costa Rican Colón' },
  { code: 'GTQ', symbol: 'Q',   name: 'Guatemalan Quetzal' },
  { code: 'HNL', symbol: 'L',   name: 'Honduran Lempira' },
  { code: 'NIO', symbol: 'C$',  name: 'Nicaraguan Córdoba' },
  { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso' },
  { code: 'TTD', symbol: 'TT$', name: 'Trinidad & Tobago Dollar' },
  { code: 'JMD', symbol: 'J$',  name: 'Jamaican Dollar' },
  { code: 'KZT', symbol: '₸',   name: 'Kazakhstani Tenge' },
  { code: 'UZS', symbol: "so'm",name: 'Uzbekistani Som' },
  { code: 'AMD', symbol: '֏',   name: 'Armenian Dram' },
  { code: 'GEL', symbol: '₾',   name: 'Georgian Lari' },
  { code: 'AZN', symbol: '₼',   name: 'Azerbaijani Manat' },
  { code: 'BYN', symbol: 'Br',  name: 'Belarusian Ruble' },
  { code: 'MDL', symbol: 'L',   name: 'Moldovan Leu' },
  { code: 'BGN', symbol: 'лв',  name: 'Bulgarian Lev' },
  { code: 'HRK', symbol: 'kn',  name: 'Croatian Kuna' },
  { code: 'RSD', symbol: 'din', name: 'Serbian Dinar' },
  { code: 'BAM', symbol: 'KM',  name: 'Bosnia-Herzegovina Mark' },
  { code: 'MKD', symbol: 'den', name: 'Macedonian Denar' },
  { code: 'ALL', symbol: 'L',   name: 'Albanian Lek' },
  { code: 'ISK', symbol: 'kr',  name: 'Icelandic Króna' },
  { code: 'MNT', symbol: '₮',   name: 'Mongolian Tögrög' },
  { code: 'MMK', symbol: 'K',   name: 'Myanmar Kyat' },
  { code: 'KHR', symbol: '៛',   name: 'Cambodian Riel' },
  { code: 'LAK', symbol: '₭',   name: 'Lao Kip' },
  { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar' },
  { code: 'MOP', symbol: 'P',   name: 'Macanese Pataca' },
  { code: 'BND', symbol: 'B$',  name: 'Brunei Dollar' },
  { code: 'MVR', symbol: 'Rf',  name: 'Maldivian Rufiyaa' },
  { code: 'BTN', symbol: 'Nu',  name: 'Bhutanese Ngultrum' },
  { code: 'AFN', symbol: '؋',   name: 'Afghan Afghani' },
  { code: 'IRR', symbol: '﷼',   name: 'Iranian Rial' },
  { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar' },
  { code: 'SYP', symbol: '£',   name: 'Syrian Pound' },
  { code: 'LBP', symbol: 'ل.ل', name: 'Lebanese Pound' },
  { code: 'YER', symbol: '﷼',   name: 'Yemeni Rial' },
  { code: 'DJF', symbol: 'Fr',  name: 'Djiboutian Franc' },
  { code: 'SOS', symbol: 'Sh',  name: 'Somali Shilling' },
  { code: 'SDG', symbol: 'ج.س', name: 'Sudanese Pound' },
  { code: 'LYD', symbol: 'ل.د', name: 'Libyan Dinar' },
  { code: 'MZN', symbol: 'MT',  name: 'Mozambican Metical' },
  { code: 'ZMW', symbol: 'ZK',  name: 'Zambian Kwacha' },
  { code: 'BWP', symbol: 'P',   name: 'Botswana Pula' },
  { code: 'NAD', symbol: 'N$',  name: 'Namibian Dollar' },
  { code: 'MWK', symbol: 'MK',  name: 'Malawian Kwacha' },
  { code: 'RWF', symbol: 'Fr',  name: 'Rwandan Franc' },
  { code: 'BIF', symbol: 'Fr',  name: 'Burundian Franc' },
  { code: 'CDF', symbol: 'Fr',  name: 'Congolese Franc' },
  { code: 'GMD', symbol: 'D',   name: 'Gambian Dalasi' },
  { code: 'CVE', symbol: '$',   name: 'Cape Verdean Escudo' },
  { code: 'MUR', symbol: '₨',   name: 'Mauritian Rupee' },
  { code: 'SCR', symbol: '₨',   name: 'Seychellois Rupee' },
  { code: 'MGA', symbol: 'Ar',  name: 'Malagasy Ariary' },
  { code: 'AOA', symbol: 'Kz',  name: 'Angolan Kwanza' },
  { code: 'SZL', symbol: 'L',   name: 'Swazi Lilangeni' },
  { code: 'LSL', symbol: 'L',   name: 'Lesotho Loti' },
  { code: 'PGK', symbol: 'K',   name: 'Papua New Guinean Kina' },
  { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar' },
  { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar' },
  { code: 'VUV', symbol: 'Vt',  name: 'Vanuatu Vatu' },
  { code: 'WST', symbol: 'WS$', name: 'Samoan Tālā' },
  { code: 'TOP', symbol: 'T$',  name: 'Tongan Paʻanga' },
  { code: 'PYG', symbol: '₲',   name: 'Paraguayan Guaraní' },
  { code: 'BOB', symbol: 'Bs',  name: 'Bolivian Boliviano' },
  { code: 'UYU', symbol: '$U',  name: 'Uruguayan Peso' },
  { code: 'VEF', symbol: 'Bs.F',name: 'Venezuelan Bolívar' },
  { code: 'GYD', symbol: '$',   name: 'Guyanese Dollar' },
  { code: 'SRD', symbol: '$',   name: 'Surinamese Dollar' },
  { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar' },
  { code: 'PAB', symbol: 'B/.',  name: 'Panamanian Balboa' },
];

// ─── Razorpay-supported currencies for international charging ──
// Source: https://razorpay.com/docs/payments/payments/international/
export const RAZORPAY_SUPPORTED_CURRENCIES = new Set([
  'INR', 'USD', 'EUR', 'GBP', 'AUD', 'CAD', 'SGD', 'AED',
  'SAR', 'QAR', 'BHD', 'KWD', 'OMR', 'MYR', 'HKD', 'JPY',
  'CHF', 'NZD', 'THB', 'SEK', 'NOK', 'DKK', 'ZAR', 'MXN',
  'BRL', 'NGN', 'EGP', 'KES', 'TRY', 'ILS', 'IDR', 'PHP',
  'TWD', 'KRW', 'PKR', 'BDT', 'LKR', 'NPR', 'MAD', 'RUB',
  'UAH', 'PLN', 'CZK', 'HUF', 'RON', 'BGN', 'IQD', 'JOD',
]);

// ─── Premium plan prices per currency ─────────────────────────
// Monthly plan base. Yearly = ~4x monthly.
// All amounts are in the MAJOR unit (e.g., dollars, not cents).
export const PLAN_PRICES = {
  premiumMonthly: {
    INR: 199,  USD: 2.39, EUR: 2.19, GBP: 1.89,  AUD: 3.69,
    CAD: 3.29, SGD: 3.25, AED: 8.79, SAR: 8.99,  QAR: 8.70,
    BHD: 0.90, KWD: 0.74, OMR: 0.92, MYR: 11.19, HKD: 18.69,
    JPY: 370,  CHF: 2.12, NZD: 3.97, THB: 85.7,  SEK: 25.2,
    NOK: 25.8, DKK: 16.4, ZAR: 44.0, MXN: 41.9,  BRL: 12.6,
    NGN: 3900, EGP: 118,  KES: 312,  TRY: 82.0,  ILS: 8.78,
    IDR: 38600,PHP: 138,  TWD: 77.8, KRW: 3300,  PKR: 676,
    BDT: 264,  LKR: 770,  NPR: 320,  MAD: 23.9,  RUB: 219,
    UAH: 99.0, PLN: 9.59, CZK: 56.0, HUF: 875,   RON: 10.98,
    BGN: 4.27, IQD: 3124, JOD: 1.70,
  },
  premiumYearly: {
    INR: 999,  USD: 11.99, EUR: 10.99, GBP: 9.49,  AUD: 18.49,
    CAD: 16.49,SGD: 16.25, AED: 44.0,  SAR: 45.0,  QAR: 43.5,
    BHD: 4.50, KWD: 3.70,  OMR: 4.60,  MYR: 55.99, HKD: 93.5,
    JPY: 1850, CHF: 10.60, NZD: 19.85, THB: 428,   SEK: 126,
    NOK: 129,  DKK: 82.0,  ZAR: 220,   MXN: 210,   BRL: 63.0,
    NGN: 19500,EGP: 590,   KES: 1560,  TRY: 410,   ILS: 43.9,
    IDR: 193000,PHP: 690,  TWD: 389,   KRW: 16500, PKR: 3380,
    BDT: 1320, LKR: 3850,  NPR: 1600,  MAD: 119.5, RUB: 1095,
    UAH: 495,  PLN: 47.95, CZK: 280,   HUF: 4375,  RON: 54.9,
    BGN: 21.35,IQD: 15620, JOD: 8.50,
  },
};

// ─── Country → Currency map (200+ countries) ──────────────────
export const COUNTRY_TO_CURRENCY = {
  // Asia-Pacific
  IN: 'INR', PK: 'PKR', BD: 'BDT', LK: 'LKR', NP: 'NPR',
  BT: 'BTN', MV: 'MVR', MM: 'MMK', TH: 'THB', VN: 'VND',
  KH: 'KHR', LA: 'LAK', MY: 'MYR', SG: 'SGD', ID: 'IDR',
  PH: 'PHP', BN: 'BND', TL: 'USD', CN: 'CNY', HK: 'HKD',
  MO: 'MOP', TW: 'TWD', JP: 'JPY', KR: 'KRW', KP: 'KPW',
  MN: 'MNT', AF: 'AFN', PG: 'PGK', FJ: 'FJD', SB: 'SBD',
  VU: 'VUV', WS: 'WST', TO: 'TOP', AU: 'AUD', NZ: 'NZD',
  // Middle East
  AE: 'AED', SA: 'SAR', QA: 'QAR', KW: 'KWD', BH: 'BHD',
  OM: 'OMR', JO: 'JOD', IL: 'ILS', IR: 'IRR', IQ: 'IQD',
  SY: 'SYP', LB: 'LBP', YE: 'YER', TR: 'TRY',
  // Europe
  GB: 'GBP', DE: 'EUR', FR: 'EUR', IT: 'EUR', ES: 'EUR',
  NL: 'EUR', BE: 'EUR', AT: 'EUR', PT: 'EUR', IE: 'EUR',
  FI: 'EUR', GR: 'EUR', SK: 'EUR', SI: 'EUR', LV: 'EUR',
  LT: 'EUR', EE: 'EUR', LU: 'EUR', MT: 'EUR', CY: 'EUR',
  CH: 'CHF', SE: 'SEK', NO: 'NOK', DK: 'DKK', IS: 'ISK',
  PL: 'PLN', CZ: 'CZK', HU: 'HUF', RO: 'RON', BG: 'BGN',
  HR: 'HRK', RS: 'RSD', BA: 'BAM', MK: 'MKD', AL: 'ALL',
  ME: 'EUR', XK: 'EUR', MD: 'MDL', UA: 'UAH', BY: 'BYN',
  RU: 'RUB', GE: 'GEL', AM: 'AMD', AZ: 'AZN',
  // Americas
  US: 'USD', CA: 'CAD', MX: 'MXN', BR: 'BRL', AR: 'ARS',
  CO: 'COP', CL: 'CLP', PE: 'PEN', VE: 'VEF', EC: 'USD',
  BO: 'BOB', PY: 'PYG', UY: 'UYU', GY: 'GYD', SR: 'SRD',
  GT: 'GTQ', BZ: 'BZD', HN: 'HNL', SV: 'USD', NI: 'NIO',
  CR: 'CRC', PA: 'PAB', CU: 'CUP', DO: 'DOP', HT: 'HTG',
  JM: 'JMD', TT: 'TTD', BB: 'BBD', LC: 'XCD', VC: 'XCD',
  GD: 'XCD', AG: 'XCD', DM: 'XCD', KN: 'XCD', BS: 'BSD',
  TC: 'USD', KY: 'KYD', AW: 'AWG', CW: 'ANG', PR: 'USD',
  // Africa
  ZA: 'ZAR', NG: 'NGN', KE: 'KES', GH: 'GHS', TZ: 'TZS',
  UG: 'UGX', ET: 'ETB', EG: 'EGP', MA: 'MAD', DZ: 'DZD',
  TN: 'TND', LY: 'LYD', SD: 'SDG', SO: 'SOS', DJ: 'DJF',
  ER: 'ERN', MZ: 'MZN', ZM: 'ZMW', ZW: 'ZWL', BW: 'BWP',
  NA: 'NAD', SZ: 'SZL', LS: 'LSL', MW: 'MWK', RW: 'RWF',
  BI: 'BIF', CD: 'CDF', CG: 'XAF', CM: 'XAF', CF: 'XAF',
  GA: 'XAF', GQ: 'XAF', TD: 'XAF', SN: 'XOF', ML: 'XOF',
  BF: 'XOF', GN: 'GNF', CI: 'XOF', GH2: 'GHS', TG: 'XOF',
  BJ: 'XOF', NE: 'XOF', MR: 'MRO', GM: 'GMD', GW: 'XOF',
  SL: 'SLL', LR: 'LRD', CV: 'CVE', ST: 'STD', MU: 'MUR',
  SC: 'SCR', MG: 'MGA', KM: 'KMF', AO: 'AOA',
  // Central Asia
  KZ: 'KZT', UZ: 'UZS', TM: 'TMT', TJ: 'TJS', KG: 'KGS',
};

// ─── World Countries List ──────────────────────────────────────
export const COUNTRIES = [
  { code: 'AF', name: 'Afghanistan' },
  { code: 'AL', name: 'Albania' },
  { code: 'DZ', name: 'Algeria' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AG', name: 'Antigua & Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Armenia' },
  { code: 'AU', name: 'Australia' },
  { code: 'AT', name: 'Austria' },
  { code: 'AZ', name: 'Azerbaijan' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrain' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Belarus' },
  { code: 'BE', name: 'Belgium' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BT', name: 'Bhutan' },
  { code: 'BO', name: 'Bolivia' },
  { code: 'BA', name: 'Bosnia & Herzegovina' },
  { code: 'BW', name: 'Botswana' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgaria' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cape Verde' },
  { code: 'KH', name: 'Cambodia' },
  { code: 'CM', name: 'Cameroon' },
  { code: 'CA', name: 'Canada' },
  { code: 'CF', name: 'Central African Republic' },
  { code: 'TD', name: 'Chad' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CO', name: 'Colombia' },
  { code: 'KM', name: 'Comoros' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'Congo (DRC)' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'HR', name: 'Croatia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CY', name: 'Cyprus' },
  { code: 'CZ', name: 'Czech Republic' },
  { code: 'DK', name: 'Denmark' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'Dominican Republic' },
  { code: 'EC', name: 'Ecuador' },
  { code: 'EG', name: 'Egypt' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea' },
  { code: 'ER', name: 'Eritrea' },
  { code: 'EE', name: 'Estonia' },
  { code: 'ET', name: 'Ethiopia' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finland' },
  { code: 'FR', name: 'France' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GM', name: 'Gambia' },
  { code: 'GE', name: 'Georgia' },
  { code: 'DE', name: 'Germany' },
  { code: 'GH', name: 'Ghana' },
  { code: 'GR', name: 'Greece' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GN', name: 'Guinea' },
  { code: 'GW', name: 'Guinea-Bissau' },
  { code: 'GY', name: 'Guyana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HU', name: 'Hungary' },
  { code: 'IS', name: 'Iceland' },
  { code: 'IN', name: 'India' },
  { code: 'ID', name: 'Indonesia' },
  { code: 'IR', name: 'Iran' },
  { code: 'IQ', name: 'Iraq' },
  { code: 'IE', name: 'Ireland' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Italy' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japan' },
  { code: 'JO', name: 'Jordan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'KE', name: 'Kenya' },
  { code: 'KP', name: 'North Korea' },
  { code: 'KR', name: 'South Korea' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Latvia' },
  { code: 'LB', name: 'Lebanon' },
  { code: 'LS', name: 'Lesotho' },
  { code: 'LR', name: 'Liberia' },
  { code: 'LY', name: 'Libya' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lithuania' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MW', name: 'Malawi' },
  { code: 'MY', name: 'Malaysia' },
  { code: 'MV', name: 'Maldives' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MR', name: 'Mauritania' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MX', name: 'Mexico' },
  { code: 'MD', name: 'Moldova' },
  { code: 'MC', name: 'Monaco' },
  { code: 'MN', name: 'Mongolia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MA', name: 'Morocco' },
  { code: 'MZ', name: 'Mozambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namibia' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Netherlands' },
  { code: 'NZ', name: 'New Zealand' },
  { code: 'NI', name: 'Nicaragua' },
  { code: 'NE', name: 'Niger' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'MK', name: 'North Macedonia' },
  { code: 'NO', name: 'Norway' },
  { code: 'OM', name: 'Oman' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PA', name: 'Panama' },
  { code: 'PG', name: 'Papua New Guinea' },
  { code: 'PY', name: 'Paraguay' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Philippines' },
  { code: 'PL', name: 'Poland' },
  { code: 'PT', name: 'Portugal' },
  { code: 'QA', name: 'Qatar' },
  { code: 'RO', name: 'Romania' },
  { code: 'RU', name: 'Russia' },
  { code: 'RW', name: 'Rwanda' },
  { code: 'KN', name: 'Saint Kitts & Nevis' },
  { code: 'LC', name: 'Saint Lucia' },
  { code: 'VC', name: 'Saint Vincent & Grenadines' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SA', name: 'Saudi Arabia' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Serbia' },
  { code: 'SC', name: 'Seychelles' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'SG', name: 'Singapore' },
  { code: 'SK', name: 'Slovakia' },
  { code: 'SI', name: 'Slovenia' },
  { code: 'SB', name: 'Solomon Islands' },
  { code: 'SO', name: 'Somalia' },
  { code: 'ZA', name: 'South Africa' },
  { code: 'SS', name: 'South Sudan' },
  { code: 'ES', name: 'Spain' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SE', name: 'Sweden' },
  { code: 'CH', name: 'Switzerland' },
  { code: 'SY', name: 'Syria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajikistan' },
  { code: 'TZ', name: 'Tanzania' },
  { code: 'TH', name: 'Thailand' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trinidad & Tobago' },
  { code: 'TN', name: 'Tunisia' },
  { code: 'TR', name: 'Turkey' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AE', name: 'United Arab Emirates' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'US', name: 'United States' },
  { code: 'UY', name: 'Uruguay' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'YE', name: 'Yemen' },
  { code: 'ZM', name: 'Zambia' },
  { code: 'ZW', name: 'Zimbabwe' },
];

// ─── Approximate conversion rates: 1 INR → target ─────────────
export const INR_TO_CURRENCY = {
  INR: 1,       USD: 0.012,   EUR: 0.011,   GBP: 0.0094,
  AUD: 0.0183,  CAD: 0.0164,  SGD: 0.0162,  AED: 0.044,
  JPY: 1.85,    CHF: 0.0106,  HKD: 0.0937,  NZD: 0.0198,
  SEK: 0.126,   NOK: 0.129,   DKK: 0.082,   CNY: 0.087,
  KRW: 16.5,    THB: 0.43,    IDR: 193,      MYR: 0.056,
  PHP: 0.69,    VND: 300,      BDT: 1.32,    PKR: 3.38,
  LKR: 3.85,    NPR: 1.6,     SAR: 0.045,   QAR: 0.044,
  KWD: 0.0037,  BHD: 0.0045,  OMR: 0.0046,  JOD: 0.0085,
  EGP: 0.59,    ZAR: 0.22,    NGN: 19.5,    KES: 1.56,
  GHS: 0.18,    TZS: 31.5,    BRL: 0.063,   MXN: 0.21,
  ARS: 12.0,    COP: 49.5,    CLP: 11.5,    PEN: 0.045,
  TRY: 0.41,    PLN: 0.048,   CZK: 0.28,    HUF: 4.35,
  RON: 0.055,   UAH: 0.5,     RUB: 1.10,    ILS: 0.044,
  MAD: 0.12,    BGN: 0.021,   IQD: 15.7,    TWD: 0.39,
};

// ─── Helpers ───────────────────────────────────────────────────

/** Get currency code for a country code. */
export function getCurrencyForCountry(countryCode) {
  return COUNTRY_TO_CURRENCY[countryCode] || 'USD';
}

/** Get currency symbol for a given currency code. */
export function getCurrencySymbol(code) {
  if (!code) return '₹';
  const found = CURRENCIES.find(c => c.code === code.toUpperCase());
  return found ? found.symbol : code.toUpperCase() + ' ';
}

/** Get plan price for a given currency. Falls back to USD. */
export function getPlanPrice(planId, currencyCode) {
  const planMap = PLAN_PRICES[planId];
  if (!planMap) return null;
  return planMap[currencyCode] ?? planMap['USD'];
}

/**
 * Convert an INR amount to the target currency.
 * Returns a formatted string (e.g., "$2.39").
 */
export function convertFromINR(amountINR, targetCurrency) {
  const rate = INR_TO_CURRENCY[targetCurrency] ?? INR_TO_CURRENCY.USD;
  const converted = amountINR * rate;
  const symbol = getCurrencySymbol(targetCurrency);
  let formatted;
  if (converted >= 1000) formatted = Math.round(converted).toLocaleString();
  else if (converted >= 10) formatted = converted.toFixed(0);
  else if (converted >= 1) formatted = converted.toFixed(2);
  else formatted = converted.toFixed(2);
  return `${symbol}${formatted}`;
}

/** Format a price with currency symbol. */
export function formatPrice(amount, currencyCode) {
  const symbol = getCurrencySymbol(currencyCode);
  const num = Number(amount);
  if (isNaN(num)) return `${symbol}0`;
  if (num >= 1000) return `${symbol}${Math.round(num).toLocaleString()}`;
  if (num >= 1) return `${symbol}${num.toFixed(2).replace(/\.00$/, '')}`;
  return `${symbol}${num.toFixed(2)}`;
}
