import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Clock, Tag, Compass, FileDown, Save, ShieldAlert, ArrowLeft, RefreshCw } from 'lucide-react';
import { getCurrencySymbol } from '../lib/currency';

export default function ItineraryViewer({ itinerary, user, onSave, onRefine, onBack, onDownloadPDF, openPricingModal, openAuthModal, isRefining }) {
  const [openDays, setOpenDays] = useState({ 0: true }); // Open Day 1 by default

  const toggleDay = (idx) => {
    setOpenDays({
      ...openDays,
      [idx]: !openDays[idx]
    });
  };

  if (!itinerary) return null;

  const { summary, budgetBreakdown, days, localCurrencyNote } = itinerary;
  

  const currencySymbol = getCurrencySymbol(summary.currency);

  const getTypeStyle = (type) => {
    switch (type) {
      case 'travel': return 'type-travel';
      case 'stay': return 'type-stay';
      case 'food': return 'type-food';
      case 'activity': return 'type-activity';
      default: return 'type-free_time';
    }
  };

  const getTypeLabel = (type) => {
    switch (type) {
      case 'travel': return '✈️ Transit';
      case 'stay': return '🏨 Lodging';
      case 'food': return '🍽️ Food & Dining';
      case 'activity': return '🎉 Activity';
      default: return '🧘 Relax Time';
    }
  };

  return (
    <div className="itinerary-container">
      {/* Back button */}
      <div style={{ textAlign: 'left' }}>
        <button className="btn btn-outline-slate btn-sm" onClick={onBack} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.4rem' }}>
          <ArrowLeft size={14} />
          <span>Plan Another Trip</span>
        </button>
      </div>

      {/* Itinerary summary and budget breakdown */}
      <div className="itinerary-summary-panel">
        <div className="summary-details">
          <h3 className="summary-heading" style={{ textTransform: 'capitalize' }}>{summary.destination} Itinerary</h3>
          <p style={{ color: '#475569', fontSize: '0.95rem', marginTop: '-0.4rem' }}>Customized day-by-day travel map generated by TRAVNIFY.</p>
          {localCurrencyNote && (
            <div style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '0.4rem',
              background: '#FFF7ED',
              border: '1px solid rgba(242, 100, 48, 0.2)',
              color: '#92400E',
              fontSize: '0.78rem',
              fontWeight: '500',
              padding: '0.3rem 0.7rem',
              borderRadius: '8px',
              marginTop: '0.4rem'
            }}>
              🌍 {localCurrencyNote}
            </div>
          )}
          
          <div className="summary-metrics">
            <div className="metric-box">
              <div className="metric-val">{summary.totalDays}</div>
              <div className="metric-lbl">Duration</div>
            </div>
            <div className="metric-box">
              <div className="metric-val">{currencySymbol}{summary.approxTotalCost.toLocaleString()}</div>
              <div className="metric-lbl">Total Budget</div>
            </div>
            <div className="metric-box">
              <div className="metric-val">{currencySymbol}{summary.dailyAverageCost.toLocaleString()}</div>
              <div className="metric-lbl">Daily Average</div>
            </div>
          </div>
        </div>

        <div className="summary-breakdown">
          <h4 style={{ fontSize: '0.9rem', fontWeight: '700', marginBottom: '0.4rem' }}>Est. Budget Allocation</h4>
          
          <div className="breakdown-row">
            <div className="breakdown-lbls">
              <span>✈️ Transit</span>
              <span>{budgetBreakdown.transportPercent}%</span>
            </div>
            <div className="progress-bar-bg">
              <div className="progress-bar-fill" style={{ width: `${budgetBreakdown.transportPercent}%`, background: '#0284C7' }}></div>
            </div>
          </div>

          <div className="breakdown-row" style={{ marginTop: '0.4rem' }}>
            <div className="breakdown-lbls">
              <span>🏨 Stays</span>
              <span>{budgetBreakdown.stayPercent}%</span>
            </div>
            <div className="progress-bar-bg">
              <div className="progress-bar-fill" style={{ width: `${budgetBreakdown.stayPercent}%`, background: '#2C6E49' }}></div>
            </div>
          </div>

          <div className="breakdown-row" style={{ marginTop: '0.4rem' }}>
            <div className="breakdown-lbls">
              <span>🍽️ Food</span>
              <span>{budgetBreakdown.foodPercent}%</span>
            </div>
            <div className="progress-bar-bg">
              <div className="progress-bar-fill" style={{ width: `${budgetBreakdown.foodPercent}%`, background: '#E11D48' }}></div>
            </div>
          </div>

          <div className="breakdown-row" style={{ marginTop: '0.4rem' }}>
            <div className="breakdown-lbls">
              <span>🎉 Activities</span>
              <span>{budgetBreakdown.activitiesPercent}%</span>
            </div>
            <div className="progress-bar-bg">
              <div className="progress-bar-fill" style={{ width: `${budgetBreakdown.activitiesPercent}%`, background: '#7C3AED' }}></div>
            </div>
          </div>
        </div>
      </div>

      {/* Premium upsell box if user is Free/Guest */}
      {(!user || !user.isPremium) && (
        <div className="premium-upsell-banner">
          <div className="upsell-info">
            <div className="upsell-title" style={{ display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
              <ShieldAlert size={18} color="#F26430" />
              <span>Unlock full features with Premium access</span>
            </div>
            <p className="upsell-desc">Upgrade to download gorgeous PDFs, save unlimited trips, and access smart refinements!</p>
          </div>
          <button className="btn btn-primary btn-sm" onClick={openPricingModal}>
            <span>Upgrade to Premium</span>
          </button>
        </div>
      )}

      {/* Safety & Logistics Tips Panel */}
      {itinerary?.safetyAndLogistics && (
        <div style={{
          background: '#FFF',
          border: '1px solid #E2E8F0',
          borderRadius: '12px',
          padding: '1.2rem',
          marginTop: '1.2rem',
          marginBottom: '1.2rem',
          boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
          gap: '1.2rem',
          textAlign: 'left'
        }}>
          {itinerary.safetyAndLogistics.localTransportTips && (
            <div>
              <h4 style={{ fontSize: '0.9rem', fontWeight: '700', color: '#0F172A', display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.4rem' }}>
                🚗 Local Transport
              </h4>
              <p style={{ fontSize: '0.85rem', color: '#475569', margin: 0, lineHeight: '1.4' }}>
                {itinerary.safetyAndLogistics.localTransportTips}
              </p>
            </div>
          )}
          {itinerary.safetyAndLogistics.areaSafetyNotes && (
            <div>
              <h4 style={{ fontSize: '0.9rem', fontWeight: '700', color: '#0F172A', display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.4rem' }}>
                🛡️ Area Safety
              </h4>
              <p style={{ fontSize: '0.85rem', color: '#475569', margin: 0, lineHeight: '1.4' }}>
                {itinerary.safetyAndLogistics.areaSafetyNotes}
              </p>
            </div>
          )}
          {itinerary.safetyAndLogistics.moneySavingTips && (
            <div>
              <h4 style={{ fontSize: '0.9rem', fontWeight: '700', color: '#0F172A', display: 'flex', alignItems: 'center', gap: '0.4rem', marginBottom: '0.4rem' }}>
                💡 Money Saving
              </h4>
              <p style={{ fontSize: '0.85rem', color: '#475569', margin: 0, lineHeight: '1.4' }}>
                {itinerary.safetyAndLogistics.moneySavingTips}
              </p>
            </div>
          )}
        </div>
      )}

      {/* Accordion day cards */}
      <div>
        {days.map((day, idx) => {
          const isOpen = !!openDays[idx];
          return (
            <div key={idx} className="day-card">
              <div className="day-header" onClick={() => toggleDay(idx)}>
                <div className="day-header-title" style={{ display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '0.5rem', textAlign: 'left' }}>
                  <div className="day-circle">{day.dayNumber}</div>
                  <strong style={{ fontWeight: '600', fontSize: '1.15rem' }}>
                    Day {day.dayNumber}: {day.location || 'Explore City'} {day.date ? `(${day.date})` : ''}
                  </strong>
                  {day.theme && (
                    <span style={{ 
                      fontSize: '0.75rem', 
                      background: 'rgba(124, 58, 237, 0.1)', 
                      color: '#7C3AED', 
                      padding: '0.2rem 0.5rem', 
                      borderRadius: '6px',
                      fontWeight: '600',
                      marginLeft: '0.5rem'
                    }}>
                      ✨ {day.theme}
                    </span>
                  )}
                </div>
                <div>
                  {isOpen ? <ChevronUp size={20} className="text-medium" /> : <ChevronDown size={20} className="text-medium" />}
                </div>
              </div>

              {isOpen && (
                <div className="day-body" style={{ textAlign: 'left' }}>
                  {day.blocks.map((block, bIdx) => (
                    <div key={bIdx} className="time-slot">
                      <div className="time-badge">
                        <Clock size={12} style={{ display: 'inline-block', marginRight: '0.2rem', verticalAlign: 'middle' }} />
                        <span style={{ verticalAlign: 'middle' }}>{block.timeWindow || '09:00 - 11:00'}</span>
                      </div>

                      <div className="slot-card">
                        <div className="slot-header">
                          <h4 className="slot-title">{block.title}</h4>
                          <span className={`slot-type-pill ${getTypeStyle(block.type)}`}>
                            {getTypeLabel(block.type)}
                          </span>
                        </div>
                        <p className="slot-desc">{block.description}</p>
                        {block.approxCost && (typeof block.approxCost === 'object' ? block.approxCost.value > 0 : parseInt(block.approxCost) > 0) && (
                          <div className="slot-cost">
                            <span>Cost: ~ {typeof block.approxCost === 'object' ? `${getCurrencySymbol(block.approxCost.currency)}${block.approxCost.value}` : block.approxCost}</span>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}

                  {/* Day-specific practical tips/notes */}
                  {day.notes && Array.isArray(day.notes) && day.notes.length > 0 && (
                    <div style={{ 
                      marginTop: '1rem', 
                      padding: '0.8rem 1rem', 
                      background: '#F8FAFC', 
                      borderRadius: '8px', 
                      borderLeft: '4px solid #F26430'
                    }}>
                      <h5 style={{ fontSize: '0.85rem', fontWeight: '700', color: '#475569', marginBottom: '0.3rem', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                        💡 Practical Tips
                      </h5>
                      <ul style={{ margin: 0, paddingLeft: '1.2rem', fontSize: '0.85rem', color: '#64748B' }}>
                        {day.notes.map((note, nIdx) => (
                          <li key={nIdx} style={{ marginBottom: '0.2rem' }}>{note}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Sticky Action Footer Bar */}
      <div className="itinerary-actions-bar">
        {/* Left Side: Refinement Actions (requires Premium check) */}
        <div className="action-refinements-group">
          {isRefining ? (
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', fontSize: '0.88rem', color: '#F26430', fontWeight: '500' }}>
              <RefreshCw size={14} className="animate-spin" />
              <span>Applying AI Refinements...</span>
            </div>
          ) : (
            <>
              <span className="refine-lbl">Refine:</span>
              <button 
                className="btn btn-outline-slate btn-sm" 
                onClick={() => user?.isPremium ? onRefine('cheaper') : openPricingModal()}
                style={{ fontSize: '0.8rem', padding: '0.4rem 0.8rem' }}
              >
                💸 Cheaper
              </button>
              <button 
                className="btn btn-outline-slate btn-sm" 
                onClick={() => user?.isPremium ? onRefine('more_fun') : openPricingModal()}
                style={{ fontSize: '0.8rem', padding: '0.4rem 0.8rem' }}
              >
                🎉 More Fun
              </button>
              <button 
                className="btn btn-outline-slate btn-sm" 
                onClick={() => user?.isPremium ? onRefine('more_relaxed') : openPricingModal()}
                style={{ fontSize: '0.8rem', padding: '0.4rem 0.8rem' }}
              >
                🧘 More Relaxed
              </button>
            </>
          )}
        </div>

        {/* Right Side: Save & PDF actions */}
        <div style={{ display: 'flex', gap: '0.6rem', width: 'auto' }}>
          <button 
            className="btn btn-secondary btn-sm" 
            onClick={() => user ? onSave() : openAuthModal('signup')}
            style={{ fontSize: '0.82rem' }}
          >
            <Save size={14} />
            <span>Save to Account</span>
          </button>
          
          <button 
            className="btn btn-primary btn-sm"
            onClick={() => user?.isPremium ? onDownloadPDF() : openPricingModal()}
            style={{ fontSize: '0.82rem' }}
            title={user?.isPremium ? 'Download PDF' : 'Upgrade to unlock PDF download'}
          >
            <FileDown size={14} />
            <span>Download PDF</span>
          </button>
        </div>
      </div>

      {/* Mandatory Disclaimer footer, matching PRD */}
      <p className="disclaimer-text">
        All times and costs are estimates. Please verify bookings, schedules, and pricing before your travel. 
        TRAVNIFY takes no responsibility for availability, schedules, or pricing variances.
      </p>
    </div>
  );
}
